"""The "Making of" project page ("The Ride"): a UI/UX case study of how this portfolio was designed and built.

Structure follows the user's guide "UI/UX Portfolio Project: What to Include and What to Avoid" (a Claude doc,
2026-10-07): hook, overview, problem, goals and constraints, what I learned, exploration, decisions, final design,
testing, outcome, reflection. Headings state the point; every picture has a caption saying what to notice.
Facts come from the user's write-up "Building my portfolio with Claude" and from the build itself. Nothing here
is invented research: where there is no data the page says so.
Pictures come from tools/build_making.py; tools/build_flow.py turns ITEMS into the page's flow.
"""
H = lambda tx, nav=None: {"t": "h", "tx": tx, "big": False, "nav": nav or tx}          # a section: nav = its short name in the index
SUB = lambda tx: {"t": "h", "tx": tx, "big": False, "sub": True}                        # a point inside a section (not in the index)
P = lambda tx: {"t": "p", "tx": tx, "narrow": False}
Q = lambda tx: {"t": "quote", "tx": tx}
BUL = lambda *items: {"t": "list", "plain": True, "items": [list(i) for i in items]}
TAB = lambda head, *rows: {"t": "table", "head": head, "rows": [list(r) for r in rows]}
PICS = lambda *names, cap=None: {"pics": list(names), "cap": cap}                        # expanded by build_flow
RULE = {"t": "rule"}

ITEMS = [
    {"t": "lead"},
    TAB(None,
        ["My role", "Concept, UX, art direction and every design decision. Solo project; I was also the client."],
        ["Built with", "Claude (planning and prompts), Claude Code (all of the code), an AI image model (the art, to my direction)"],
        ["Timeline", "8 days, 29 September to 6 October 2026"],
        ["Platform", "Responsive web: desktop, tablet and phone"],
        ["Outcome", "Live. A scroll-driven ride through six places, a plain second view, and a case-study page for each project"]),
    RULE,

    H("The problem: my old portfolio showed my work, but nothing of how I think", "Problem"),
    P("My previous site was a standard Framer page: a hero, a tagline, four project cards. It did its job and it could have been anyone’s. I am a visual and UI/UX designer looking for a grad project, and a reviewer gives a portfolio a minute or two. In that minute the site itself is the first piece of my work they see."),
    P("So the brief I set myself was: make the portfolio a designed experience that people remember, without making them work to reach the projects."),
    PICS("old-home", cap="Before: the old site. A hero and a line of text; nothing here says who made it."),
    RULE,

    H("Goals and constraints", "Goals"),
    BUL(["Be remembered.", "The site should feel like a place, and like mine: an Indian city at night, not generic tech."],
        ["The work stays the hero.", "Whatever the world looks like, project images, reels and photos are shown at full quality and get the brightest light."],
        ["Never trap anyone.", "A reviewer in a hurry must be able to reach any project in one click, on any device."],
        ["Constraint: one person, eight days, no hand-written code.", "Everything had to be describable in a prompt and checkable by eye."],
        ["Constraint: the art comes from an image model.", "Fixed-size frames, no layers, and no guarantee that two scenes match."]),
    RULE,

    H("What I learned early, and what each lesson changed", "Insights"),
    P("This was a self-initiated project, so there were no user interviews. The research was references, and looking hard at each build as it came back. Three things I learned shaped everything after:"),
    BUL(["A themed world competes with the work.", "In the first build the scenery was louder than the projects. That became the core rule: the world is drawn, the work is not, and the room dims around whatever you are looking at."],
        ["A journey needs a map.", "Once the site was a walk through places, nobody could tell where they were or how much was left. The navigation became a metro line with six stops that fill in as you go."],
        ["Scenes generated separately drift apart.", "A dozen images made in separate sessions stopped looking like one world. That led to a written style bible, and in the end to redrawing everything."]),
    PICS("v1-drain", "v1-subway", cap="The first build, in pixel art. Notice how the scenery and the project board fight for attention."),
    RULE,

    H("Exploring: one street in six styles, then twelve palettes", "Exploration"),
    P("The first complete version was pixel art, and it worked from start to finish. But each place had its own look: the subway cold cyan, the cinema deep red, the gallery brown, the rooftop pink. Each scene looked good alone; together they looked like five different games. I stopped adding to it and went back to frame one."),
    PICS("v1-lobby", "v1-gallery-mid", "v1-rooftop", cap="Three places from version one. Each has a different palette and a different idea of light."),
    SUB("Six styles, one scene"),
    P("I redrew the same street in six illustration styles so that only the style changed. I rejected the stark red-and-black print (too harsh behind project images), the blue line drawing (no sense of night) and the pastel (too soft for the city). The grainy screen print stayed: flat shapes, hard-edged light, and clean at any screen size, which pixel art was not."),
    PICS("explore-styles", cap="Same street, six styles. The grainy screen print, bottom row centre, was chosen."),
    SUB("Twelve palettes, one style"),
    P("Then the chosen style went through twelve colour passes. The loud ones fought with the project images that would sit on the billboards. Navy, red and gold let the work win."),
    PICS("explore-colours", cap="Twelve colour passes. The navy, red and gold versions in the bottom row became the palette."),
    SUB("The character, round by round"),
    PICS("explore-character", cap="Character sheets from soft and pale, left, to the bolder final on the right, lit like the street he stands in."),
    RULE,

    H("Five decisions, and what each one cost", "Decisions"),
    SUB("1. Scrolling is the only control"),
    P("Scroll moves him forward; scroll back and he walks back. I gave up free movement and anything game-like that needs keys. In return it works the same with a mouse wheel, a trackpad or a thumb, and nobody has to learn anything."),
    SUB("2. The world is illustrated; the work is not"),
    P("Project images, reels and photos are never restyled to match the world. They sit in the world’s frames at full quality, and the scene darkens around the one you are at. The cost is a less seamless picture; the gain is that the work is always the brightest thing on screen."),
    PICS("shot-subway", "shot-gallery", cap="The station and the gallery fall dark around the project or photo he has stopped at."),
    SUB("3. Throw away a finished version"),
    P("Replacing all the pixel art meant regenerating every scene and the character, and re-measuring every position in the code. It cost about two of the eight days. It bought one world instead of five, and a style that holds up on large screens."),
    PICS("pixel-street", "shot-hero", cap="Street, before and after. Same layout and billboards; one palette and one kind of light."),
    PICS("v1-cinema", "shot-cinema", cap="Cinema, before and after. The screen became the player itself, with the reels as posters on the stage."),
    SUB("4. Navigation as a metro line"),
    P("The first nav was a row of section names, and I found it confusing in a site that moves sideways and down. The metro line shows six stops, fills in behind you and lets you jump to any stop. It takes more room than a menu icon, which I accepted because orientation mattered more."),
    SUB("5. A second, plain way in"),
    P("Not everyone wants a ride. A Ride | Simple switch sits in the top corner on every screen: Simple is the same content as an ordinary scrolling page. It meant designing and maintaining the site twice, and it is the reason the ride is allowed to be slow."),
    PICS("shot-simple", "shot-simple2", cap="The Simple view: the same projects with no journey. Reachable from every screen."),
    RULE,

    H("The final design", "Final design"),
    P("One night, six stops. Each place is a section of the site, and the character’s action tells you what the section is for."),
    TAB(["Place", "Section", "What happens"],
        ["Street", "Hero", "The logo and title card; he waits, then sets off"],
        ["Drain", "About", "He drops down a manhole while the About text lights up word by word"],
        ["Subway", "Projects", "Each project is a billboard that comes forward as he reaches it"],
        ["Cinema", "Reels", "The screen is the video player"],
        ["Gallery", "Photography", "The view centres on each frame and the lights go down around it"],
        ["Rooftop", "Contact", "He sits down, the string lights come on and the contact details appear"]),
    PICS("shot-hero", cap="Street. The title card sits over a dimmed street; only the windows, lamps and the passing metro stay lit."),
    PICS("shot-drain", "shot-lobby", cap="The drain doubles as the About section; the stairs lead up to the cinema lobby."),
    PICS("shot-stairs", "shot-rooftop", cap="The back stairs to the gallery, and the rooftop that ends the night with the contact details."),
    SUB("States, not just the happy path"),
    BUL(["Loading:", "an arcade cabinet counts in while the art loads, so the first frame is never half-drawn."],
        ["Empty:", "reels I have not uploaded yet show “Coming soon” on the cinema screen instead of a broken player."],
        ["Small screens:", "the metro line moves to the bottom edge within thumb reach, and wide scenes are extended so they fill a tall screen."],
        ["Reduced motion:", "for people who turn animation off, the looping effects stop and the Simple view is one tap away."]),
    PICS("arcade", "shot-preloader", cap="Loading state. Left, the cabinet as generated; right, with its screen and counter coded on top."),
    PICS("phone-ride", "phone-subway", "phone-simple", cap="On a phone: the hero, a project in the subway, and the Simple view."),
    SUB("The system underneath"),
    P("Six inks, used the same way in every scene. Three typefaces across the whole site: Talina for headings, Satoshi for text, Hind for Hindi. Two rules do most of the work: about two thirds of every image stays dark, and light always falls off from cream to gold to a red rim."),
    {"t": "swatches", "inks": [["Ember Night", "#24080D", "Sky, buildings, road"], ["Harbour Navy", "#233049", "Cool shadows, shutters"], ["Monsoon Blue", "#23517B", "Horizon, river, wet road"],
                               ["Signal Red", "#A91314", "Signs, awnings, the rim of every glow"], ["Lamp Gold", "#FDD672", "Windows, bulbs, lamp cones"], ["Moon Cream", "#FCECBB", "Moon, stars, the centre of every light"]]},
    SUB("Project pages"),
    P("Every project opens on a full-screen picture with the facts in the corner, runs its pictures edge to edge and keeps a chapter list at the side. Each takes its colours from the project, and the type stays the same."),
    PICS("shot-all", cap="All projects. Boards hang dim and light up on hover, the same behaviour as the subway billboards."),
    RULE,

    H("Testing: I was the first user, and these are the things that failed", "Testing"),
    P("There has been no outside usability testing yet, and I would rather say so than dress it up. What I did do was review every build on a laptop, a narrow window and a phone, and send back what was wrong. The fixes that mattered:"),
    TAB(["What I found", "What changed"],
        ["The navigation was confusing", "Rebuilt as the metro line, chosen from three working options"],
        ["Project cards were getting lost in the station", "The card he stands at grows, the station dims, and it holds still mid-screen"],
        ["The first redesigned card looked tacky", "Stripped back to a flat ground, one hairline edge and quiet type"],
        ["The opening screen lagged once deployed", "A few effects were forcing a redraw every frame; removing them took it from about 16 frames a second to a steady 60 in testing"],
        ["The Simple view looked generic, twice", "Rebuilt from visual references I supplied instead of from a description"],
        ["The staircase lighting felt like a horror film", "Relit like the rooftop: warm lamps on deep blue"],
        ["The last project card was cut off at the edge", "The station now lets a card overlap the next scene"],
        ["Photos in the gallery sat half off screen", "The view now eases over to centre each frame"]),
    RULE,

    H("How I worked with AI, and where my judgment sat", "Working with AI"),
    P("I wrote no code by hand and drew no final art by hand. What I did was decide what the site should be, describe it precisely, and reject what was wrong. Claude planned and wrote prompts with me, Claude Code built and measured, and an image model drew to a style guide I set."),
    BUL(["Follow-ups as diffs.", "Each prompt said what to keep, what to change and what not to touch. A cleanup prompt for the street removed shrines, extra signs, plants and cranes, closed every shop but the general store and kept three billboards blank."],
        ["Point at the picture, not the angle.", "Image models flatten side doors. “Set into an angled recess, like the door in the bottom right of the attached image” worked where degrees did not."],
        ["Plan every image for the code.", "Billboards, posters and frames were generated as flat magenta so real work could be dropped in; the character’s lowest foot is always the anchor."],
        ["Investigate before changing.", "Wiring prompts began with “report back on how scenes, camera and floor lines work now”."],
        ["Options, then a choice.", "For type, navigation, the reel player and the project pages, Claude Code built two or three working versions on a scratch page. I picked one and the rest were deleted."]),
    PICS("raw-gallery", "raw-arcade", cap="Straight from the image model. The magenta areas are slots, replaced in code by a photo, a screen and a title."),
    P("Limits I hit: the model produces fixed-size frames, so sharpness on large screens is capped; separately generated panels each had their own perspective, so floors were redrawn flat and side-on to line up; and copy written by AI came back too polished. My About text went through five rounds of cutting, and the line above my reels is the one I wrote myself."),
    RULE,

    H("Outcome, and what I would measure", "Outcome"),
    P("The site is live. It has six places, a Simple view, six project pages and a preloader, built in eight days and over a hundred recorded changes. I do not have usage numbers yet, so I will not quote any. These are the ones I would track:"),
    BUL(["", "How many visitors stay in the ride and how many switch to Simple, and when."],
        ["", "How far down the ride people get before leaving."],
        ["", "Time from landing to opening a first project."],
        ["", "Whether people who use the metro line jump ahead or go back."]),
    SUB("Accessibility"),
    P("The Simple view is the accessible route: ordinary headings, links and reading order. The ride has a skip link to the projects, visible keyboard focus, labelled controls and respects the reduced-motion setting. What is not done: colour contrast has not been audited against a standard, and the ride is a long way to travel by keyboard alone."),
    RULE,

    H("What I learned, and what I would do differently", "Reflection"),
    BUL(["", "Decide the style before building the world. Choosing it after cost two days of redrawing."],
        ["", "Test with other people sooner. Every fix above came from me, and I already know where everything is."],
        ["", "The second view was the best decision I made. It removed the pressure for the ride to be fast."],
        ["", "Directing AI is a design skill. The work was in the brief, the constraints and the no."]),
]
