"""The "Making of" project page: how this portfolio was built.

The words come from the user's own write-up ("Building my portfolio with Claude", a Claude doc, 2026-10-06),
kept in its order, with a few parts added from the build itself (marked ADDED). Pictures come from
tools/build_making.py. tools/build_flow.py turns ITEMS into the page's flow.
"""
H = lambda tx, big=False: {"t": "h", "tx": tx, "big": big}
P = lambda tx: {"t": "p", "tx": tx, "narrow": False}
Q = lambda tx: {"t": "quote", "tx": tx}
BUL = lambda *items: {"t": "list", "plain": True, "items": [list(i) for i in items]}
NUM = lambda *items: {"t": "list", "items": [list(i) for i in items]}
TAB = lambda head, *rows: {"t": "table", "head": head, "rows": [list(r) for r in rows]}
PICS = lambda *names, cap=None, fill=None: {"pics": list(names), "cap": cap, "fill": fill}     # expanded by build_flow
RULE = {"t": "rule"}

ITEMS = [
    {"t": "lead"},
    TAB(None,
        ["Role", "Concept, art direction, prompt writing"],
        ["Build", "Claude Code, scroll-driven 2D scenes"],
        ["Planning and prompts", "Claude (chat)"],
        ["Art", "AI image generation, directed with reference images, a world style guide and a colour bible"],
        ["Core rule", "The world is illustrated; the work inside it is shown at full quality"]),
    RULE,

    H("The concept"),
    P("The site is one night in the city: it opens at late-night neon and ends on a rooftop under string lights. Scrolling moves the character forward, and when you stop he goes idle."),
    TAB(["Location", "Site section", "What the character does"],
        ["Street", "Hero: name and intro", "Stands idle, then starts walking"],
        ["Drain", "About", "Slides the manhole cover aside and drops down"],
        ["Subway", "Projects, one per billboard", "Walks the platform past the billboards"],
        ["Cinema", "Reels", "Climbs to the lobby, enters the hall, watches the screen"],
        ["Gallery", "Photography", "Walks slowly along the framed wall"],
        ["Rooftop", "Footer: contact and socials", "Sits down with a chai as the lights come on"]),
    P("I started from three references: a retro game screen with a HUD, a moody night street, and a dense vertical neon city. Claude merged them into a first prompt for a modern Indian street, then into a world style guide that every location had to follow. Its pillars:"),
    BUL(["Hard edges everywhere.", "No blur or soft gradients on the world or its UI."],
        ["The world is drawn; the work is not.", "Project images, reels and photos sit at full quality inside the world's frames, so the work stands out."],
        ["Each location has its own key light.", "Fluorescent light in the subway, red velvet and a projector beam in the cinema, gallery spotlights, string lights on the roof."],
        ["Real Indian texture.", "Chai stalls, autos, hand-painted signs in Hindi and English, local train stations and old single-screen cinemas, not generic cyberpunk."],
        ["Game UI throughout.", "Speech bubbles, chunky buttons, and a small metro-line map that shows where you are and doubles as navigation."]),
    H("Building the world"),
    P("Every scene went through the same loop: write an image prompt, generate, critique the result with Claude, then write a targeted follow-up that changed one thing and froze everything else. Once a scene looked right, a second prompt told Claude Code how to wire it in."),
    H("The character"),
    P("I gave Claude two photos of myself and it turned them into a sprite brief: messy dark hair, thick black glasses, a hoop earring, a silver kada, a loose overshirt over a white tee, wide trousers and white sneakers. From there I generated sprite sheets for walking, idling, and climbing stairs up and down, with one rule that made them usable in code: the lowest foot is always the anchor, and a raised foot sits exactly one step higher."),
    PICS("pixel-sheet", cap="The first character: a pixel sprite sheet with every pose the journey needed."),
    H("Scene by scene"),
    BUL(["Street (hero):", "the first render was crowded. A cleanup prompt removed shrines, extra signs, plants, bollards and cranes, closed every shop but the general store, calmed the sky and kept three billboards blank. I left open sky between the top two billboards so my name could sit there, and added a manhole cover in the road as the hint for the next scene."],
        ["Drain:", "a short shaft, about one screen of scroll, with a shrinking circle of street light above and subway light growing below. The About text lights up word by word on the way down."],
        ["Subway (projects):", "a station platform where each project lives on a billboard. Vertical scroll turns into a walk along the platform."],
        ["Stairwell and cinema lobby:", "the old stairs scene and ticket lobby were replaced with one cross-section image: platform below, a single flight of stairs, and a lobby above with a ticket booth, snack counter and reel posters."],
        ["Theatre (reels):", "the character pushes through the doors and stands before the screen, which is the reel player itself. I also redirected the exit doors so they face into the hall instead of at the viewer."],
        ["Gallery (photography):", "generated as three panels that line up edge to edge, entrance to main hall to exit, every frame a blank slot for my photos."],
        ["Rooftop (footer):", "water tanks, a parapet, a bench under string lights and the city skyline at the end of the night."],
        ["Preloader:", "an old arcade cabinet in a neighbourhood game parlour, replacing a CSS mock-up. The screen, title and loading bar are coded on top of the image."]),
    PICS("pixel-street", "v1-drain", cap="Version one. The street as first generated, and the fall down the drain with the About text."),
    PICS("v1-subway-in", "v1-subway", cap="The subway: landing on the platform, and a project on its billboard."),
    PICS("v1-stairs", "v1-lobby", cap="Up the stairs to the cinema lobby."),
    PICS("v1-cinema", "v1-gallery-in", cap="The cinema hall and the gallery entrance."),
    PICS("v1-gallery-mid", "v1-rooftop", cap="The gallery wall, and the rooftop at dawn that closed the night."),
    H("What made the art usable"),
    P("Generating scenes that a character can actually walk through taught me more than any single prompt:"),
    BUL(["Leave the content slots flat magenta.", "Every billboard, poster and frame was generated as solid #FF00FF so real project images could be dropped in with code."],
        ["Size everything to the character.", "My first gallery felt giant. The fix was a shared spec: the character is 20% of the image height with feet at 72%, and every rail, door and frame is placed relative to him."],
        ["No converging lines on floors.", "Each panel had its own vanishing point, so neighbours never lined up. Flat side-on views with vertical plank seams tile cleanly."],
        ["Point at the picture, not the angle.", "Image models flatten side doors. “Set into an angled recess, like the door in the bottom right of the attached image” worked where degrees did not."],
        ["Align seams with measured lines.", "To join the subway to the stairwell, Claude Code solved scale and offset from two shared lines, the platform floor and the yellow safety strip, instead of guessing."]),
    PICS("raw-gallery", "raw-arcade", cap="Straight from the image model: the gallery entrance and the arcade cabinet, with magenta where the photo, the screen and the title would go."),
    RULE,

    H("Why I pivoted"),
    P("By this point the whole ride worked in pixel art, start to finish. But with a dozen scenes generated in separate sessions, the world had stopped looking like one place: the street was neon and rain, the subway cold cyan, the cinema deep red, the gallery brown, the rooftop pink. Each scene looked good alone, and together they looked like five different games."),
    P("So I stopped adding to it and went back to the first frame. Instead of fixing scenes one by one, I decided to choose one illustration style, write it down as a bible, and redraw everything to obey it."),
    H("Choosing a style"),
    P("I took the street scene and recreated it in several illustration styles, each from a reference image: a painted poster, a stark red and black print, a flat pastel, a blue line drawing, a grainy screen print, and a loose brush drawing. Same street, same billboards, same manhole, so the only thing changing was the style."),
    PICS("explore-styles", cap="One street, six styles. The grainy screen print (bottom row, middle) was the one that stuck."),
    P("The one that stuck was the grainy, risograph-like screen print: large flat shapes, uneven ink and hard-edged light. It kept the night mood of the pixel version, and it stays clean at any size, which pixel art never did on large screens."),
    H("Finding the palette"),
    P("With the style chosen, I ran the same image through colour after colour: reds, navy, magenta, electric blue, violet, deep blue with gold. Seeing them side by side made the choice easy. The loud ones fought with the project images that would sit on the billboards; the navy, red and gold one let them win."),
    PICS("explore-colours", cap="Twelve colour passes of the chosen style."),
    P("From the chosen image I built Monsoon Night, an HTML style and colour guide with the master illustration, six detail crops and a strict palette."),
    {"t": "swatches", "inks": [["Ember Night", "#24080D", "Upper sky, buildings, trees, road"], ["Harbour Navy", "#233049", "Cool shadows, shutters, skyline towers"], ["Monsoon Blue", "#23517B", "Horizon sky, river, sheen on the road"],
                               ["Signal Red", "#A91314", "Signs, awnings, the outer rim of every glow"], ["Lamp Gold", "#FDD672", "Lit windows, bulbs, lamp cones near their source"], ["Moon Cream", "#FCECBB", "Moon, stars, billboards, the hottest centres of light"]]},
    P("The rules that do the most work:"),
    BUL(["", "About two thirds of every image sits in the dark inks."],
        ["", "Light always falls off cream core, then gold, then a red rim, then night."],
        ["", "Red is for edges and accents, never backgrounds."],
        ["", "The style paragraph, palette block and negative prompt are copied word for word; only the subject paragraph changes per scene."]),
    P("I then told Claude to treat the guide as the bible for every prompt. It now flags anything off-palette and offers an on-palette swap."),
    H("Redrawing the character"),
    P("The pixel sprite no longer belonged in this world, so he was redrawn too. The first passes were soft and pale, like a storybook; each round pushed him closer to the street he stands in, until he was lit in the same six inks."),
    PICS("explore-character", cap="Character sheets, round by round, ending with the bolder one on the right."),
    PICS("sheet-poses", "sheet-walk", cap="The final set: turnaround, expressions, wave, cheer and a seat with chai; twelve frames of walking each way."),
    H("The revamp"),
    P("Then every scene was regenerated under the bible and wired back in. The journey, the camera and the code underneath stayed; only the measurements changed. Below, each place as it was and as it is now."),
    PICS("pixel-street", "shot-hero", cap="Street"),
    PICS("v1-drain-wide", "shot-drain", cap="Drain"),
    PICS("v1-subway", "shot-subway", cap="Subway"),
    PICS("v1-lobby", "shot-lobby", cap="Cinema lobby"),
    PICS("v1-cinema", "shot-cinema", cap="Cinema hall"),
    PICS("v1-gallery-mid", "shot-gallery", cap="Gallery"),
    PICS("v1-rooftop", "shot-rooftop", cap="Rooftop"),
    PICS("raw-arcade", "shot-preloader", cap="Preloader"),
    RULE,

    H("Words"),
    P("The copy went through the same loop as the visuals: generate, cut, cut again. My About text started as a long, playful paragraph and ended three sentences long."),
    TAB(["Round", "What I asked", "What changed"],
        ["1", "Turn my notes into a paragraph", "A long draft covering films, food, travel and quirks"],
        ["2", "Shorten it for the About section", "Half the length, quirks kept"],
        ["3", "Make it playful", "Jokes added; felt too polished"],
        ["4", "Remove “powered” and the list of quirks", "Tighter, more direct"],
        ["5", "Fix a line that sounded incomplete, drop the closer", "Final version"]),
    P("The final About text:"),
    Q("I’m Anish Shah, a 20-year-old designer who starts with the story and lets the visuals follow, always building alongside people. I find my inspiration in films that change the way I see the world, food that brings me joy, and travel that keeps my imagination restless. I translate feelings into design, so the work doesn’t just look good but truly means something."),
    P("For the header above my reels, every polished option got a “naaahhh” until I wrote my own: “i make content, i just forget to post it.” Lowercase and honest beat clever."),
    RULE,

    H("How I prompted"),
    P("The biggest skill this project built was describing motion and space precisely enough that a machine gets it right the first time. Six habits did most of the work:"),
    NUM(["Design the world before the pages.", "Mapping each section to a place and an action (projects on billboards, reels in a cinema) gave every later prompt a clear job."],
        ["Write follow-ups as diffs.", "Each prompt said what to keep, what to change and what not to touch, ending with the rule that matters most, since the end of a prompt carries the most weight."],
        ["Point at the picture, not the angle.", "Referring to a door or detail already in the image worked better than describing it in degrees."],
        ["Give images a shared spec.", "One block for style, palette and human scale, pasted into every prompt, kept separately generated scenes consistent."],
        ["Plan every image for the code.", "Blank slots, blank billboards, anchor feet on sprites and measured seam lines meant each image was built to be wired up, not just looked at."],
        ["Make Claude Code investigate first.", "Wiring prompts began with “report back on how scenes, camera and floor lines work now” before changing anything."]),
    RULE,

    # ADDED: how the site works, from the build itself
    H("Under the hood"),
    P("The site is plain HTML, CSS and JavaScript with no framework and no build step. Everything the character does is a function of how far the page has scrolled."),
    BUL(["One world, one camera.", "Every location is a picture placed in a single large world. The scroll position is turned into a point on a path through it, and that point decides where he stands, which pose he is in and where the camera looks."],
        ["A path made of segments.", "Walk the street, open the manhole, fall, walk the platform, climb, sit, and so on: about thirty segments, each with a start, an end, a pose and a camera rule. Scrolling back plays it all in reverse."],
        ["Sprites drawn frame by frame.", "The character is drawn to a canvas from three sheets: walking and poses, the fall down the drain, and the stairs. On stairs his strides are tied to the scroll, so each step lands on a tread."],
        ["Art measured, not eyeballed.", "Small Python scripts cut each painting into the parts the page needs (the metro that crosses the overpass, the railings he walks behind, the seats in front of him) and print the coordinates the code uses."],
        ["Content in one file.", "Projects, reels, photos and contact details live in a single data file, so adding a project never touches the engine."]),
    TAB(["", "In numbers"],
        ["Built in", "8 days, 29 September to 6 October 2026"],
        ["Changes recorded", "113 commits"],
        ["Scenes", "8, joined into one world"],
        ["Character frames", "About 90, across three sprite sheets"],
        ["Typefaces", "3: Talina, Satoshi and Hind"],
        ["Code written by hand", "None"]),
    H("Decisions along the way"),
    P("Most of the build was choosing. For each open question Claude Code built two or three working options on a scratch page, I picked one, and the rest were thrown away."),
    BUL(["Type.", "Compared Inter Display, Satoshi, Talina and Montserrat on the real screens; chose Talina for headings with Satoshi for text."],
        ["Navigation.", "The nav was confusing, so it became a metro line: six stops that fill in as the night goes on."],
        ["Reels.", "The cinema screen became the player itself, with the reels as posters on the stage."],
        ["A second way in.", "Not everyone wants a ride, so there is a Simple view: the same content as a retro desktop, with pixel-edged windows you can drag."],
        ["Project pages.", "Three layouts were mocked up (gallery, editorial, cinematic). Cinematic won: a full-screen opening, pictures edge to edge and a chapter list at the side. Each project keeps its own colours."],
        ["Smoothness.", "The opening screen lagged once it was live. Measuring showed a few effects forcing the browser to redraw every frame; replacing them took it from about 16 frames a second while scrolling to a steady 60 in testing."]),
    PICS("shot-simple", "shot-simple2", cap="The Simple view: the same portfolio without the ride."),
    RULE,

    H("Timeline"),
    TAB(["Date", "Milestone"],
        ["29 Sep", "Character sprite designed from my photos; first scroll-driven mock of the site"],
        ["30 Sep", "World style guide and journey; subway, stairwell, theatre, gallery, rooftop and preloader scenes"],
        ["2 Oct", "Street scene recreated in several illustration styles; Monsoon Night guide built; all pixel art replaced"],
        ["3 Oct", "Monsoon Night adopted as the bible for every prompt; character redrawn in the six inks"],
        ["4 Oct", "Typography, metro-line navigation, the reels player, the Simple view, sharper art for high-density screens"],
        ["5 Oct", "The hero title card and its lights, project pages, performance work, first deploy"],
        ["6 Oct", "Footer, the project pages' cinematic layout, a fifth project, focus lighting in the subway and gallery"]),
]
